import type { AppState } from './types'

export const seedState: AppState = {

  // ─── Custom field definitions for client projects ────────────────────────────
  customFieldDefs: [
    { id:'cf1', label:'Architect',            type:'text',    required:false, options:[],                                                                     order:0, section:'Team' },
    { id:'cf2', label:'Building Contractor',  type:'text',    required:false, options:[],                                                                     order:1, section:'Team' },
    { id:'cf3', label:'Electrical Engineer',  type:'text',    required:false, options:[],                                                                     order:2, section:'Team' },
    { id:'cf4', label:'Mechanical Engineer',  type:'text',    required:false, options:[],                                                                     order:3, section:'Team' },
    { id:'cf5', label:'Product Series',       type:'select',  required:false, options:['ARK','FT ColdPlunge','Auroom','Custom','Mr Steam','Hybrid'],          order:4, section:'Product' },
    { id:'cf6', label:'Stove / Heater',       type:'select',  required:false, options:['IKI Kiuas 9kw','Huum Drop 9kw','Saunum Air 9kw','Narvi 9kw','None'], order:5, section:'Product' },
    { id:'cf7', label:'Referral Source',      type:'select',  required:false, options:['Word of mouth','Instagram','Architect referral','Contractor','Direct','LivTerra'], order:6, section:'Sales' },
    { id:'cf8', label:'Site Access Notes',    type:'textarea',required:false, options:[],                                                                     order:7, section:'Site' },
    { id:'cf9', label:'COJ / Electrical Approval', type:'checkbox', required:false, options:[],                                                              order:8, section:'Compliance' },
  ],

  // ─── Client Projects ─────────────────────────────────────────────────────────
  clients: [
    {
      id:'c1', client:'Tsholo Safari Lodge',   contactName:'Tsholo',     location:'Stellenbosch, WC',
      category:'hospitality',  products:'Custom Sauna + Ice Bath ×2 + Mr Steam + Shower + Cariitti Lighting',
      status:'active',  value:850000, progress:55, stage:'Mechanical & Electrical',
      lead:'Ari', startDate:'2026-01-15', endDate:'2026-08-30',
      notes:'Major lodge wellness suite. Multiple phases. Coordinate Tyron (structure), CMB (mechanical), Garreth (drawings).',
      customFields:{ cf1:'Garreth', cf3:'CMB Mechanical Engineers', cf5:'ARK', cf6:'IKI Kiuas 9kw', cf7:'Word of mouth' },
    },
    {
      id:'c2', client:'House Daniel Ginzberg', contactName:'Daniel',     location:'5th Ave, Illovo, JHB',
      category:'residential', products:'ARK 5 Pavilion + Custom Sauna + Ice Bath ×2',
      status:'active',  value:580000, progress:70, stage:'Cladding & Benches',
      lead:'Ari', startDate:'2026-02-01', endDate:'2026-07-15',
      notes:'Ark 5 with custom steel structure. Tyron fabricating frame. Afrim 3D renders approved.',
      customFields:{ cf3:'Tyron Engineer', cf5:'ARK', cf6:'Huum Drop 9kw', cf7:'Architect referral' },
    },
    {
      id:'c3', client:'Cardova Lodge 1',       contactName:'Cardova',    location:'Stellenbosch Wine Farm',
      category:'collab',      products:'Full Wellness Centre: Sauna + Ice Bath + Steam + Outdoor Deck',
      status:'active',  value:680000, progress:30, stage:'Frame & Foundation',
      lead:'Ari', startDate:'2026-03-01', endDate:'2026-09-30',
      notes:'Wine farm lodge wellness centre. Lodge 2 to follow. Garreth on drawings.',
      customFields:{ cf1:'Garreth', cf5:'ARK', cf6:'Saunum Air 9kw', cf7:'Direct' },
    },
    {
      id:'c4', client:'Miranda Plewman',        contactName:'Miranda',    location:'Stellenbosch, WC',
      category:'residential', products:'Custom Indoor Sauna — Thermory + IKI Kiuas',
      status:'active',  value:245000, progress:75, stage:'Electrical First Fix',
      lead:'Ari', startDate:'2026-03-10', endDate:'2026-06-30',
      notes:'Multiple proposals sent (Apr + May + Jun 2025). Final scope confirmed. Nic Plewman co-owner.',
      customFields:{ cf5:'Custom', cf6:'IKI Kiuas 9kw', cf7:'Word of mouth' },
    },
    {
      id:'c5', client:'House Oyster Bay',       contactName:'',           location:'Camps Bay, Cape Town',
      category:'residential', products:'Indoor Sauna + Optional Cold Plunge (FT ColdPlunge1)',
      status:'active',  value:265000, progress:60, stage:'Insulation & Cladding',
      lead:'Ari', startDate:'2026-03-20', endDate:'2026-07-01',
      notes:'Sauna proposal with 3 cold plunge options. Client selected FT ColdPlunge1.',
      customFields:{ cf5:'FT ColdPlunge', cf6:'Narvi 9kw', cf7:'Instagram' },
    },
    {
      id:'c6', client:'DDP x LivWell',          contactName:'',           location:'Cape Town',
      category:'collab',      products:'Indoor + Outdoor Wellness Installation',
      status:'active',  value:320000, progress:45, stage:'Plumbing & Electrical',
      lead:'Ari', startDate:'2026-04-01', endDate:'2026-07-30',
      notes:'Collaboration project. Electrical and plumbing requirements scoped.',
      customFields:{ cf5:'Hybrid', cf7:'Direct' },
    },
    {
      id:'c7', client:'House Orlin',            contactName:'Orlin',      location:'Unknown',
      category:'residential', products:'Custom Sauna (Auroom Kaia) + Ice Bath',
      status:'active',  value:310000, progress:40, stage:'Structure Complete',
      lead:'Ari', startDate:'2026-04-10', endDate:'2026-07-20',
      notes:'Multiple proposals (1-4 sent). Morris & Co wooden structure. Auroom Kaia model selected.',
      customFields:{ cf5:'Auroom', cf6:'Saunum Air 9kw', cf7:'Word of mouth' },
    },
    {
      id:'c8', client:'House Augusta',          contactName:'Augusta',    location:'Constantia, Cape Town',
      category:'residential', products:'Indoor Sauna + FT ColdPlunge2',
      status:'active',  value:320000, progress:45, stage:'Framing',
      lead:'Ari', startDate:'2026-04-15', endDate:'2026-08-01',
      notes:'Costings tracked in Excel. Custom timber specification.',
      customFields:{ cf5:'FT ColdPlunge', cf6:'Huum Drop 9kw', cf7:'Architect referral' },
    },
    {
      id:'c9', client:'House Dawn 7',           contactName:'Ina',        location:'Constantia, Cape Town',
      category:'residential', products:'FT ColdPlunge1 + Outdoor Shower',
      status:'qa',      value:145000, progress:92, stage:'Final Punch List',
      lead:'Ari', startDate:'2026-02-01', endDate:'2026-06-20',
      notes:'Near completion. QA walkthrough scheduled.',
      customFields:{ cf5:'FT ColdPlunge', cf7:'Word of mouth' },
    },
    {
      id:'c10',client:'House Simon Medburn',    contactName:'Simon',      location:'Rhodes 14, Camps Bay area',
      category:'residential', products:'Indoor Sauna + Custom Benches + Structural Supports',
      status:'complete',value:195000, progress:100, stage:'Handed Over',
      lead:'Ari', startDate:'2025-11-01', endDate:'2026-03-15',
      notes:'Engineer drawings completed. Variation orders tracked. Invoiced and paid.',
      customFields:{ cf5:'Custom', cf6:'IKI Kiuas 9kw', cf7:'Contractor' },
    },
    {
      id:'c11',client:'Steenberg',              contactName:'',           location:'Steenberg, Cape Town',
      category:'residential', products:'Custom Indoor Sauna',
      status:'complete',value:175000, progress:100, stage:'Handed Over',
      lead:'Ari', startDate:'2025-10-15', endDate:'2026-02-28',
      notes:'Complete. Photo shoot completed for portfolio.',
      customFields:{ cf5:'Custom', cf6:'Huum Drop 9kw', cf7:'Instagram' },
    },
    {
      id:'c12',client:'House Bee Diem',         contactName:'',           location:'Ruyterplaats, Hout Bay',
      category:'residential', products:'Outdoor Sauna + FT ColdPlunge1 + Deck',
      status:'proposal', value:285000, progress:0, stage:'Proposal Sent',
      lead:'Ari', startDate:'', endDate:'',
      notes:'Revised proposal sent. House Ruyterplaats Hout Bay — awaiting sign-off.',
      customFields:{ cf5:'FT ColdPlunge', cf6:'Narvi 9kw', cf7:'Word of mouth' },
    },
    {
      id:'c13',client:'Karen Camps Bay',        contactName:'Karen',      location:'Bakoven / Camps Bay, CT',
      category:'residential', products:'FT Terra 5 + Cold Plunge + Accessories',
      status:'proposal', value:380000, progress:0, stage:'Pricelist Sent',
      lead:'Ari', startDate:'', endDate:'',
      notes:'Karen Terra 5 Pricelist 2025 sent. Bakoven apartment. April 2025 meeting.',
      customFields:{ cf5:'FT ColdPlunge', cf7:'Architect referral' },
    },
    {
      id:'c14',client:'House Morningside',      contactName:'',           location:'Morningside, JHB',
      category:'residential', products:'Custom Indoor Sauna — Option A or B',
      status:'proposal', value:235000, progress:0, stage:'Two Options Presented',
      lead:'Ari', startDate:'', endDate:'',
      notes:'Two proposal versions (A and B) presented. Decision pending.',
      customFields:{ cf5:'Custom', cf6:'Saunum Air 9kw', cf7:'Direct' },
    },
    {
      id:'c15',client:'House Clifton Bungalow', contactName:'',           location:'Clifton, Cape Town',
      category:'residential', products:'Custom Outdoor Sauna',
      status:'proposal', value:195000, progress:0, stage:'Concept Stage',
      lead:'Ari', startDate:'', endDate:'',
      notes:'Tight site. Clifton bungalow — space constraints to manage.',
      customFields:{ cf5:'Custom', cf7:'Instagram' },
    },
    {
      id:'c16',client:'House Orlin Leopard Creek', contactName:'Orlin',   location:'Leopard Creek, Limpopo',
      category:'hospitality', products:'Lodge Sauna + Ice Bath Suite',
      status:'lead',    value:420000, progress:0, stage:'Initial Discussion',
      lead:'Ari', startDate:'', endDate:'',
      notes:'Second Orlin property — bush lodge. Remote site logistics to plan.',
      customFields:{ cf5:'ARK', cf7:'Word of mouth' },
    },
    {
      id:'c17',client:'House Peral Valley',     contactName:'',           location:'Pearl Valley, WC',
      category:'residential', products:'Custom Sauna + Accessories',
      status:'lead',    value:180000, progress:0, stage:'Initial Discussion',
      lead:'Ari', startDate:'', endDate:'',
      notes:'', customFields:{ cf7:'Architect referral' },
    },
    {
      id:'c18',client:'House Vanessa Cowing',   contactName:'Vanessa',    location:'Unknown',
      category:'residential', products:'Sauna + FT ColdPlunge1',
      status:'lead',    value:230000, progress:0, stage:'Initial Discussion',
      lead:'Ari', startDate:'', endDate:'',
      notes:'', customFields:{ cf5:'FT ColdPlunge', cf7:'Instagram' },
    },
    {
      id:'c19',client:'House Courtney Mulder',  contactName:'Courtney',   location:'Unknown',
      category:'residential', products:'Sauna',
      status:'lead',    value:165000, progress:0, stage:'Initial Discussion',
      lead:'Ari', startDate:'', endDate:'',
      notes:'', customFields:{ cf7:'Word of mouth' },
    },
    {
      id:'c20',client:'Cardova Lodge 2',        contactName:'Cardova',    location:'Stellenbosch Wine Farm',
      category:'collab',      products:'Wellness Centre Lodge 2 — Sauna + Cold Plunge + Deck',
      status:'proposal', value:580000, progress:0, stage:'Drawings Under Review',
      lead:'Ari', startDate:'', endDate:'',
      notes:'Lodge 2 follows Lodge 1. Garreth drawings under review. SketchUp files ready.',
      customFields:{ cf1:'Garreth', cf5:'ARK', cf7:'Direct' },
    },
    {
      id:'c21',client:'House Dricuss',          contactName:'Dricuss',    location:'Unknown',
      category:'residential', products:'Custom Build',
      status:'lead',    value:210000, progress:0, stage:'Initial Discussion',
      lead:'Ari', startDate:'', endDate:'',
      notes:'', customFields:{},
    },
  ],

  // ─── Product Catalogue ───────────────────────────────────────────────────────
  products: [
    // Cold
    { id:'pr1',  name:'FT ColdPlunge1',        category:'cold',      description:'Entry-level cold plunge. Chiller 750W, 400L. Ideal for residential installations.', priceZAR:92000,  supplier:'Bropool',       leadTimeWeeks:10, status:'available', notes:'Most popular residential unit.' },
    { id:'pr2',  name:'FT ColdPlunge2',         category:'cold',      description:'Mid-range cold plunge. Chiller 1500W, 600L. Stainless liner, touchscreen control.',  priceZAR:118000, supplier:'Bropool',       leadTimeWeeks:10, status:'available', notes:'' },
    { id:'pr3',  name:'FT NeptunoSpa',          category:'cold',      description:'Premium spa cold plunge. Ozone + UV + chiller. 800L. Perfect for hospitality.',     priceZAR:185000, supplier:'Bropool',       leadTimeWeeks:12, status:'available', notes:'Tsholo and lodge spec.' },
    { id:'pr4',  name:'FT VulcanoSpa',          category:'cold',      description:'Top of range. 1000L spa with dual chiller + heating. Hot/cold switchable.',         priceZAR:218000, supplier:'Bropool',       leadTimeWeeks:14, status:'available', notes:'Ideal for hospitality.' },
    // Hot
    { id:'pr5',  name:'Bropool Hot Tub 4-seat', category:'hot',       description:'4-seat outdoor hot tub. Acrylic shell, 6 jets, LED lighting, 220V.',               priceZAR:112000, supplier:'Bropool',       leadTimeWeeks:10, status:'available', notes:'' },
    { id:'pr6',  name:'Bropool Hot Tub 6-seat', category:'hot',       description:'6-seat outdoor hot tub. Acrylic shell, 8 jets, LED, cover included.',              priceZAR:145000, supplier:'Bropool',       leadTimeWeeks:10, status:'available', notes:'' },
    { id:'pr7',  name:'Bropool Ice Making Unit',category:'hot',       description:'Ice maker for cold plunge pools. 30kg/day capacity. Standalone unit.',             priceZAR:38000,  supplier:'Bropool',       leadTimeWeeks:8,  status:'available', notes:'' },
    // Hybrid
    { id:'pr8',  name:'Nordsprings Combo',       category:'hybrid',    description:'Nordic hot/cold combo. Plunge pool + mini sauna unit. Outdoor rated.',            priceZAR:195000, supplier:'mRP / bropool', leadTimeWeeks:12, status:'pre-order', notes:'New 2026 model.' },
    // Sauna
    { id:'pr9',  name:'ARK Sauna Cabin',         category:'ark',       description:'LivWell ARK — bespoke outdoor sauna cabin. Custom steel + timber. In-house build.',priceZAR:285000, supplier:'In-house',      leadTimeWeeks:8,  status:'available', notes:'Tyron fabricates frame. Thermory cladding.' },
    { id:'pr10', name:'ARK Pergola Pavilion',    category:'ark',       description:'ARK Pergola — full outdoor wellness pavilion. Sauna + deck + accessories.',       priceZAR:320000, supplier:'In-house',      leadTimeWeeks:10, status:'available', notes:'Cardova Lodge spec.' },
    { id:'pr11', name:'Auroom Kaia',             category:'sauna',     description:'Imported Estonian barrel sauna. Cedar. 4-person. Ready to install.',             priceZAR:145000, supplier:'Auroom',        leadTimeWeeks:14, status:'available', notes:'Orlin project used this model.' },
    { id:'pr12', name:'Auroom VMS',              category:'sauna',     description:'Auroom VMS modular indoor sauna system. Multiple configs available.',            priceZAR:168000, supplier:'Auroom',        leadTimeWeeks:14, status:'available', notes:'' },
    { id:'pr13', name:'Custom Cedar Sauna',      category:'sauna',     description:'Fully bespoke cedar sauna built in-house. Any size, any layout.',               priceZAR:155000, supplier:'In-house',      leadTimeWeeks:6,  status:'available', notes:'Base price. Final quote per project.' },
    // Steam
    { id:'pr14', name:'Mr Steam MS90E',          category:'steam',     description:'Commercial steam generator 9kw. 240–450 cu ft. Digital control.',               priceZAR:65000,  supplier:'Mr Steam',      leadTimeWeeks:6,  status:'available', notes:'Tsholo spec.' },
    // Accessories
    { id:'pr15', name:'IKI Kiuas 9kw',           category:'accessory', description:'Finnish IKI electric kiuas. 9kw. Stainless. Top-loading stones.',              priceZAR:18500,  supplier:'IKI',           leadTimeWeeks:8,  status:'available', notes:'' },
    { id:'pr16', name:'Huum Drop 9kw',           category:'accessory', description:'Huum Drop sauna heater. 9kw. Minimal Nordic design.',                          priceZAR:22000,  supplier:'Huum',          leadTimeWeeks:8,  status:'available', notes:'' },
    { id:'pr17', name:'Saunum Air 9kw',          category:'accessory', description:'Saunum Air sauna heater with air circulation system. Softer heat distribution.',priceZAR:28000,  supplier:'Saunum',        leadTimeWeeks:10, status:'available', notes:'' },
    { id:'pr18', name:'Narvi NC 9kw',            category:'accessory', description:'Finnish Narvi sauna heater. Classic design, high stone capacity.',             priceZAR:16800,  supplier:'Narvi',         leadTimeWeeks:10, status:'available', notes:'' },
    { id:'pr19', name:'Cariitti LED Sauna Kit',  category:'accessory', description:'Cariitti fibre optic LED sauna lighting kit. IP67. Full ceiling + wall set.',   priceZAR:8500,   supplier:'Cariitti',      leadTimeWeeks:6,  status:'available', notes:'' },
    { id:'pr20', name:'Rento Bucket + Ladle',    category:'accessory', description:'Finnish birch sauna bucket and ladle set. Rento brand.',                       priceZAR:2800,   supplier:'Rento',         leadTimeWeeks:4,  status:'available', notes:'' },
    { id:'pr21', name:'Thermory Bench Kit',      category:'accessory', description:'Thermory heat-treated aspen bench kit. Pre-cut, pre-drilled for standard sizes.',priceZAR:12000, supplier:'Thermory',      leadTimeWeeks:8,  status:'available', notes:'' },
  ],

  // ─── Suppliers ───────────────────────────────────────────────────────────────
  suppliers: [
    { id:'s1',  name:'Bropool',                 country:'China',       category:'plunge-tubs',  contactName:'Bropool Sales',    email:'sales@bropool.com',           leadTimeDays:70, status:'active', notes:'Main cold plunge + hot tub supplier. Sea freight to JHB/CT.' },
    { id:'s2',  name:'Huum',                    country:'Estonia',     category:'stoves',        contactName:'Huum Export',      email:'export@huum.eu',              leadTimeDays:55, status:'active', notes:'Drop and Cliff heater range. EUR pricing.' },
    { id:'s3',  name:'IKI',                     country:'Finland',     category:'stoves',        contactName:'IKI Sales',        email:'',                            leadTimeDays:60, status:'active', notes:'Kiuas heaters. Premium Finnish brand.' },
    { id:'s4',  name:'Saunum',                  country:'Estonia',     category:'stoves',        contactName:'Saunum Team',      email:'',                            leadTimeDays:55, status:'active', notes:'Air circulation sauna heater — softer heat.' },
    { id:'s5',  name:'Narvi',                   country:'Finland',     category:'stoves',        contactName:'Narvi',            email:'',                            leadTimeDays:60, status:'active', notes:'Classic Finnish kiuas. High stone capacity.' },
    { id:'s6',  name:'Thermory',                country:'Estonia',     category:'timber',        contactName:'Thermory SA rep',  email:'',                            leadTimeDays:45, status:'active', notes:'Heat-treated aspen and pine. Main cladding + bench material.' },
    { id:'s7',  name:'EmotionWood',             country:'Estonia',     category:'timber',        contactName:'EW Sales',         email:'',                            leadTimeDays:50, status:'active', notes:'Premium timber interiors and cladding.' },
    { id:'s8',  name:'Auroom',                  country:'Estonia',     category:'timber',        contactName:'Auroom Export',    email:'',                            leadTimeDays:60, status:'active', notes:'Kaia, VMS and CLT modular sauna kits.' },
    { id:'s9',  name:'Nikkarien',               country:'Finland',     category:'timber',        contactName:'Nikkarien',        email:'',                            leadTimeDays:65, status:'active', notes:'Finnish sauna wood products.' },
    { id:'s10', name:'Rento',                   country:'Finland',     category:'timber',        contactName:'Rento',            email:'',                            leadTimeDays:55, status:'active', notes:'Sauna accessories — buckets, ladles, fragrances.' },
    { id:'s11', name:'Cariitti',                country:'Finland',     category:'lighting',      contactName:'Cariitti',         email:'',                            leadTimeDays:55, status:'active', notes:'Fibre optic sauna lighting systems. High-end installations.' },
    { id:'s12', name:'Amorin Cork',             country:'Portugal',    category:'cork',          contactName:'Amorin SA',        email:'',                            leadTimeDays:30, status:'active', notes:'Cork insulation boards for sauna wall + ceiling.' },
    { id:'s13', name:'Aerothane',               country:'South Africa',category:'insulation',    contactName:'Aerothane',        email:'',                            leadTimeDays:7,  status:'active', notes:'Spray foam insulation. Local. Used for sauna shells.' },
    { id:'s14', name:'Raptor / Matthew Frobus', country:'South Africa',category:'fabrication',   contactName:'Matthew Frobus',   email:'',                            leadTimeDays:14, status:'active', notes:'Decks and structural steel for outdoor installations. Cape Town.' },
    { id:'s15', name:'Artvion',                 country:'South Africa',category:'design-3d',     contactName:'Artvion',          email:'',                            leadTimeDays:10, status:'active', notes:'3D renders and visualisations. Used for proposals and marketing.' },
    { id:'s16', name:'Mr Steam',                country:'USA',         category:'steam',         contactName:'Mr Steam',         email:'',                            leadTimeDays:30, status:'active', notes:'Steam generator units. MS90E for most residential jobs.' },
    { id:'s17', name:'Rothoblaas',              country:'Italy',       category:'fabrication',   contactName:'Rothoblaas SA',    email:'',                            leadTimeDays:14, status:'active', notes:'Timber fixings, brackets, and connectors.' },
    { id:'s18', name:'Alpha Alloys',            country:'South Africa',category:'steel',         contactName:'Alpha Alloys',     email:'',                            leadTimeDays:7,  status:'active', notes:'Structural steel sections. Johannesburg.' },
    { id:'s19', name:'Vulcan Steel',            country:'South Africa',category:'steel',         contactName:'Vulcan Steel',     email:'',                            leadTimeDays:7,  status:'active', notes:'Steel and metal supplies.' },
    { id:'s20', name:'Noags Timber',            country:'South Africa',category:'timber',        contactName:'Noags',            email:'',                            leadTimeDays:5,  status:'active', notes:'Local timber. Pine, meranti, structural.' },
    { id:'s21', name:'Atlantic Glass CT',       country:'South Africa',category:'glass',         contactName:'Atlantic Glass',   email:'',                            leadTimeDays:14, status:'active', notes:'Sauna glass doors and panels. Cape Town.' },
    { id:'s22', name:'Insulpro',                country:'South Africa',category:'insulation',    contactName:'Insulpro',         email:'',                            leadTimeDays:7,  status:'active', notes:'Insulation materials for wall builds.' },
    { id:'s23', name:'Tyron Engineer',          country:'South Africa',category:'fabrication',   contactName:'Tyron',            email:'',                            leadTimeDays:7,  status:'active', notes:'In-house fabrication. ARK frames, steel housing, custom metal.' },
    { id:'s24', name:'Jaquar Sanitary',         country:'India',       category:'sanitary',      contactName:'Jaquar SA',        email:'',                            leadTimeDays:21, status:'active', notes:'Shower fittings and sanitary ware for wellness suites.' },
    { id:'s25', name:'ISS',                     country:'South Africa',category:'logistics',     contactName:'ISS Logistics',    email:'',                            leadTimeDays:3,  status:'active', notes:'Local logistics and clearing.' },
  ],

  // ─── Manufacturing Jobs ───────────────────────────────────────────────────────
  manufacturingJobs: [
    {
      id:'mfg1', jobNo:'MFG-026-001', projectId:'c3', product:'ARK Pergola Frame — Cardova Lodge 1',
      status:'assembly', priority:'high', assignedTo:'Tyron', dueDate:'2026-07-15',
      notes:'Steel frame fabricated. Timber cladding next. Coordinate with Raptor for on-site decking.',
      cutlist: [
        { id:'cl1',  material:'75×75 SHS Steel', description:'Upright columns',       length:3000, width:75, thickness:4, qty:8,  done:true },
        { id:'cl2',  material:'100×50 RHS Steel', description:'Roof purlins',          length:3600, width:100,thickness:4, qty:6,  done:true },
        { id:'cl3',  material:'Thermory 28mm',   description:'Exterior wall cladding', length:2800, width:120,thickness:28,qty:24, done:false },
        { id:'cl4',  material:'Thermory 28mm',   description:'Roof decking boards',    length:3600, width:120,thickness:28,qty:18, done:false },
        { id:'cl5',  material:'Cedar 20mm',      description:'Interior ceiling lining', length:2800, width:90, thickness:20,qty:32, done:false },
      ],
    },
    {
      id:'mfg2', jobNo:'MFG-026-002', projectId:'c1', product:'Custom Sauna Frame — Tsholo Lodge',
      status:'cutting', priority:'urgent', assignedTo:'Tyron', dueDate:'2026-07-01',
      notes:'Urgent — site ready to receive. Dimensions: 3.2m × 2.4m × 2.3m. IKI 9kw stove spec.',
      cutlist: [
        { id:'cl6',  material:'Cedar 20mm',     description:'Back wall panels',     length:2300, width:120,thickness:20,qty:22, done:false },
        { id:'cl7',  material:'Cedar 20mm',     description:'Side wall panels',     length:2400, width:120,thickness:20,qty:18, done:false },
        { id:'cl8',  material:'Thermory 42mm',  description:'Top bench',           length:3200, width:450,thickness:42,qty:1,  done:false },
        { id:'cl9',  material:'Thermory 42mm',  description:'Lower bench',         length:3200, width:350,thickness:42,qty:1,  done:false },
        { id:'cl10', material:'Pine 45×45 CLS', description:'Bench support frame',  length:650,  width:45, thickness:45,qty:12, done:false },
      ],
    },
    {
      id:'mfg3', jobNo:'MFG-026-003', projectId:'c2', product:'Ice Bath Steel Housing ×2 — Daniel Ginzberg',
      status:'welding', priority:'high', assignedTo:'Tyron', dueDate:'2026-07-08',
      notes:'Two custom steel housings for FT NeptunoSpa units. 316 stainless interior panels.',
      cutlist: [
        { id:'cl11', material:'3mm Mild Steel',    description:'Side panels',      length:1800, width:800, thickness:3, qty:8, done:true },
        { id:'cl12', material:'3mm Mild Steel',    description:'Base panels',      length:1200, width:800, thickness:3, qty:4, done:true },
        { id:'cl13', material:'316 Stainless 2mm', description:'Interior liner',  length:1800, width:800, thickness:2, qty:8, done:false },
      ],
    },
    {
      id:'mfg4', jobNo:'MFG-026-004', projectId:'c7', product:'Auroom Kaia Assembly — House Orlin',
      status:'pending', priority:'medium', assignedTo:'Workshop', dueDate:'2026-08-01',
      notes:'Auroom Kaia delivered from Estonia. Pre-cut — assembly only. Afrim on-site for supervision.',
      cutlist: [],
    },
  ],

  // ─── Invoices (INV-00xx series) ──────────────────────────────────────────────
  invoices: [
    { id:'inv1',  invoiceNo:'INV-0078', projectId:'c1',  client:'Tsholo Safari Lodge',   amount:425000, status:'paid',    issueDate:'2026-01-20', dueDate:'2026-02-04', notes:'50% deposit on project commencement.' },
    { id:'inv2',  invoiceNo:'INV-0079', projectId:'c2',  client:'House Daniel Ginzberg', amount:290000, status:'paid',    issueDate:'2026-02-05', dueDate:'2026-02-20', notes:'50% deposit.' },
    { id:'inv3',  invoiceNo:'INV-0080', projectId:'c4',  client:'Miranda Plewman',        amount:122500, status:'paid',    issueDate:'2026-03-12', dueDate:'2026-03-27', notes:'50% deposit.' },
    { id:'inv4',  invoiceNo:'INV-0081', projectId:'c5',  client:'House Oyster Bay',       amount:132500, status:'paid',    issueDate:'2026-03-22', dueDate:'2026-04-06', notes:'50% deposit.' },
    { id:'inv5',  invoiceNo:'INV-0082', projectId:'c3',  client:'Cardova Lodge 1',        amount:340000, status:'paid',    issueDate:'2026-03-05', dueDate:'2026-03-20', notes:'50% deposit on lodge contract.' },
    { id:'inv6',  invoiceNo:'INV-0083', projectId:'c9',  client:'House Dawn 7',           amount:145000, status:'paid',    issueDate:'2026-04-10', dueDate:'2026-04-25', notes:'Full payment on completion.' },
    { id:'inv7',  invoiceNo:'INV-0084', projectId:'c10', client:'House Simon Medburn',    amount:195000, status:'paid',    issueDate:'2026-03-01', dueDate:'2026-03-16', notes:'Final payment. Project complete.' },
    { id:'inv8',  invoiceNo:'INV-0085', projectId:'c1',  client:'Tsholo Safari Lodge',   amount:212500, status:'sent',    issueDate:'2026-06-01', dueDate:'2026-06-16', notes:'50% progress payment at mechanical stage.' },
    { id:'inv9',  invoiceNo:'INV-0086', projectId:'c3',  client:'Cardova Lodge 1',        amount:170000, status:'sent',    issueDate:'2026-06-10', dueDate:'2026-06-25', notes:'25% progress payment.' },
    { id:'inv10', invoiceNo:'INV-0087', projectId:'c7',  client:'House Orlin',            amount:155000, status:'sent',    issueDate:'2026-06-05', dueDate:'2026-06-20', notes:'50% deposit on confirmed scope.' },
    { id:'inv11', invoiceNo:'INV-0088', projectId:'c6',  client:'DDP x LivWell',          amount:160000, status:'sent',    issueDate:'2026-06-15', dueDate:'2026-06-30', notes:'50% deposit on collab project.' },
    { id:'inv12', invoiceNo:'INV-0089', projectId:'c8',  client:'House Augusta',          amount:160000, status:'overdue', issueDate:'2026-05-20', dueDate:'2026-06-04', notes:'50% deposit — OVERDUE. Follow up Ari.' },
    { id:'inv13', invoiceNo:'INV-0090', projectId:'c13', client:'Karen Camps Bay',        amount:190000, status:'draft',   issueDate:'2026-06-21', dueDate:'2026-07-05', notes:'Awaiting client sign-off on pricelist.' },
    { id:'inv14', invoiceNo:'INV-0091', projectId:'c4',  client:'Miranda Plewman',        amount:122500, status:'draft',   issueDate:'2026-06-21', dueDate:'2026-07-05', notes:'Progress payment — 75% milestone.' },
  ],

  // ─── Expenses ─────────────────────────────────────────────────────────────────
  expenses: [
    { id:'ex1',  projectId:'c1',  description:'Bropool FT NeptunoSpa ×2 (Tsholo)',           category:'materials',  amount:370000, supplier:'Bropool',           date:'2026-01-25', notes:'Sea freight included. Landed JHB.' },
    { id:'ex2',  projectId:'c2',  description:'ARK 5 steel sections — Alpha Alloys',         category:'materials',  amount:48000,  supplier:'Alpha Alloys',      date:'2026-02-10', notes:'' },
    { id:'ex3',  projectId:'c2',  description:'Afrim 3D renders — Ginzberg ARK 5',           category:'equipment',  amount:18000,  supplier:'Artvion',           date:'2026-02-15', notes:'Final approved render pack.' },
    { id:'ex4',  projectId:'c3',  description:'Thermory cladding (Cardova Lodge 1)',         category:'materials',  amount:52000,  supplier:'Thermory',          date:'2026-03-08', notes:'Exterior cladding order.' },
    { id:'ex5',  projectId:'c3',  description:'Raptor decking — Lodge 1 platform',           category:'labour',     amount:35000,  supplier:'Raptor',            date:'2026-04-05', notes:'Matthew Frobus on site for 3 days.' },
    { id:'ex6',  projectId:'c4',  description:'IKI Kiuas 9kw ×1 (Plewman)',                 category:'materials',  amount:18500,  supplier:'IKI',               date:'2026-03-15', notes:'' },
    { id:'ex7',  projectId:'c4',  description:'Amorin Cork insulation boards',               category:'materials',  amount:14500,  supplier:'Amorin Cork',       date:'2026-03-18', notes:'' },
    { id:'ex8',  projectId:'c1',  description:'Mr Steam MS90E unit (Tsholo)',                category:'materials',  amount:65000,  supplier:'Mr Steam',          date:'2026-04-01', notes:'Steam generator for main wellness suite.' },
    { id:'ex9',  projectId:'c1',  description:'Cariitti LED Sauna Kit (Tsholo)',             category:'materials',  amount:8500,   supplier:'Cariitti',          date:'2026-04-05', notes:'' },
    { id:'ex10', projectId:'c1',  description:'Tyron — Sauna frame fabrication (Tsholo)',   category:'labour',     amount:45000,  supplier:'Tyron Engineer',    date:'2026-05-10', notes:'Frame + bench structure + door frame.' },
    { id:'ex11', projectId:'c5',  description:'Bropool FT ColdPlunge1 (Oyster Bay)',        category:'materials',  amount:92000,  supplier:'Bropool',           date:'2026-03-25', notes:'' },
    { id:'ex12', projectId:'c7',  description:'Auroom Kaia delivery (Orlin)',               category:'logistics',  amount:28000,  supplier:'ISS',               date:'2026-04-20', notes:'Customs clearance + delivery to site.' },
    { id:'ex13', projectId:'c2',  description:'Aerothane spray foam insulation (Ginzberg)', category:'materials',  amount:12000,  supplier:'Aerothane',         date:'2026-05-20', notes:'' },
    { id:'ex14', projectId:'c6',  description:'Atlantic Glass — sauna door (DDP)',          category:'materials',  amount:9500,   supplier:'Atlantic Glass CT', date:'2026-05-28', notes:'8mm tempered glass sauna door.' },
    { id:'ex15', projectId:'c8',  description:'Huum Drop 9kw (Augusta)',                    category:'materials',  amount:22000,  supplier:'Huum',              date:'2026-04-18', notes:'' },
  ],

  // ─── Design & R&D Jobs ───────────────────────────────────────────────────────
  designJobs: [
    { id:'d1', projectId:'c1',  title:'Tsholo Lodge — Full Concept + Mechanical Spec',        type:'specification',      assignedTo:'Garreth',   status:'approved',    dueDate:'2026-02-28', notes:'Drawings complete. Coordinated with CMB for plumbing + electrical spec.' },
    { id:'d2', projectId:'c2',  title:'Daniel Ginzberg ARK 5 — 3D Render Pack',              type:'3d-render',          assignedTo:'Afrim',     status:'approved',    dueDate:'2026-03-01', notes:'Full interior + exterior renders. Client approved. Used in proposal.' },
    { id:'d3', projectId:'c3',  title:'Cardova Lodge 1 — Wellness Centre Drawings',          type:'technical-drawing',  assignedTo:'Garreth',   status:'review',      dueDate:'2026-06-30', notes:'Lodge 1 structural drawings. SketchUp model complete. Review pending.' },
    { id:'d4', projectId:'c14', title:'House Morningside — Option A + B Sauna Proposals',   type:'proposal',           assignedTo:'Ari',       status:'approved',    dueDate:'2026-05-15', notes:'Two layout options presented. Client comparing.' },
    { id:'d5', projectId:'c16', title:'House Orlin Leopard Creek — Concept Brief',          type:'concept',            assignedTo:'Afrim',     status:'briefed',     dueDate:'2026-07-15', notes:'Remote bush lodge. Biophilic design brief. Solar-aware spec.' },
    { id:'d6', projectId:'c20', title:'Cardova Lodge 2 — Wellness Centre Drawings',         type:'technical-drawing',  assignedTo:'Garreth',   status:'in-progress', dueDate:'2026-07-30', notes:'Follows Lodge 1 design language. SketchUp file lodges 2.skp ready.' },
    { id:'d7', projectId:'c5',  title:'House Oyster Bay — Interior Spec + Proposal',        type:'proposal',           assignedTo:'Ari',       status:'approved',    dueDate:'2026-04-01', notes:'Three cold plunge options presented. Option 1 selected.' },
    { id:'d8', projectId:'c7',  title:'House Orlin — Sauna + Ice Bath Proposals 1-4',       type:'proposal',           assignedTo:'Ari',       status:'approved',    dueDate:'2026-05-01', notes:'Multiple revisions. Final scope: Auroom Kaia + FT ColdPlunge1.' },
    { id:'d9', projectId:'',    title:'LivTerra Outdoor Wellness Range — Lookbook 2026',     type:'animation',          assignedTo:'Artvion',   status:'in-progress', dueDate:'2026-08-01', notes:'Future brand project. Livterra outdoor furniture + wellness range.' },
  ],

  // ─── Collabs ─────────────────────────────────────────────────────────────────
  collabs: [
    {
      id:'col1', name:'Cardova Lodge 1', partner:'Cardova Wine Farm', type:'lodge', status:'active',
      value:680000, products:'ARK Pergola + Sauna + FT NeptunoSpa + Steam + Deck',
      description:'Full wellness centre for wine farm boutique lodge. Lodge 1 of 2. Garreth on drawings, Tyron on frame, Raptor on decking.',
      notes:'On site from July 2026. Lodge 2 to follow in Q4.',
    },
    {
      id:'col2', name:'Cardova Lodge 2', partner:'Cardova Wine Farm', type:'lodge', status:'proposal',
      value:580000, products:'Sauna + Cold Plunge + Outdoor Wellness Deck',
      description:'Second lodge wellness centre on same wine farm. Slightly smaller than Lodge 1.',
      notes:'Drawings underway with Garreth. SketchUp file complete. Will begin after Lodge 1 is handed over.',
    },
    {
      id:'col3', name:'DDP x LivWell', partner:'DDP', type:'commercial', status:'active',
      value:320000, products:'Indoor + Outdoor Wellness Installation',
      description:'Commercial collaboration. Electrical and plumbing requirements scoped. Indoor and outdoor units.',
      notes:'Plumbing and electrical layout completed. On site from June 2026.',
    },
    {
      id:'col4', name:'LivTerra — Outdoor Wellness Range', partner:'Future Brand', type:'brand', status:'proposal',
      value:0, products:'Outdoor furniture + wellness structures + accessories',
      description:'Future brand concept: LivTerra. High-end outdoor furniture + wellness range. Lookbook in production.',
      notes:'Artvion producing lookbook. HubSpot CRM has 892 contacts pre-loaded for launch.',
    },
    {
      id:'col5', name:'Amani Collab', partner:'Amani', type:'brand', status:'proposal',
      value:0, products:'Safari wellness experience collaboration',
      description:'Safari ritual wellness brand collaboration. Deck overview shared.',
      notes:'Deck sent. Awaiting response.',
    },
  ],
}
